### ISSUE TITLE
Can we remove reqwest from fetcher implementation for auth0.

### ISSUE THREAD

**Issue by IgnorantCoder** [payper-src/suzume#14]
Now we have dependency to `reqwest` in the following.

https://github.com/payper-src/suzume/blob/a41aff7f55d1c58418a8d6cda14f74b50e14ed1f/src/auth0.rs#L106

It is better to keep fetch call function as member, and call it in the bellow code, I think.

**Comment by megumish** [comment]
Right. This library should be enable to be used fetching with not only reqwest but also others.

I will work on it.
